### ISSUE TITLE
When the keyboard pops up, the default scroll bar options do not expand, but are compressed by the keyboard

### ISSUE THREAD

**Issue by fengwu913** [cosee/alphabet_list_view#11]

**Comment by quoc-huynh-cosee** [comment]
Hi @fengwu913 can you write your issue in English? Otherwise it is hard for us to understand you.

**Comment by fengwu913** [comment]
hello @quoc-huynh-cosee   ok, my issue is

When the keyboard pops up, the default scroll bar options do not expand, but are compressed by the keyboard

**Comment by quoc-huynh-cosee** [comment]
@fengwu913 We'll have a look into that.

**Comment by quoc-huynh-cosee** [comment]
I will close the issue. If you encounter any problems, feel free to reopen it.

**Comment by fengwu913** [comment]
> Hello @fengwu913,
> 
> this is the expected behavior. The of gets resized to avoid the keyboard. The is simply another widget that resizes depending on its parent.`body``Scaffold``AlphabetListView`
> 
> This behavior is the same as in Apples Contacts-App. ![Contacts App](https://private-user-images.githubusercontent.com/48699936/274684232-f38399fe-481c-410b-8257-eeb129ff4ac2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNjI3MzMsIm5iZiI6MTcwNDI2MjQzMywicGF0aCI6Ii80ODY5OTkzNi8yNzQ2ODQyMzItZjM4Mzk5ZmUtNDgxYy00MTBiLTgyNTctZWViMTI5ZmY0YWMyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDA2MTM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyZDY0NDVlNDNmNDMyMWVkZDQ0OGEwNWJlZDc1NmQ5MTNmNjhmMmZlZDZlYjdjMjlmMTJmNzNiNTczNjhkMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dj4ze7tjMKLYa96f7T3AQ0zEZa32eYurqZXMW0zXIjE)
> 
> If you wish to alter this behavior you could set s to . would then be displayed behind the keyboard. However, this would hide the entries at the bottom of the list behind the keyboard.`Scaffold``resizeToAvoidBottomInset``false``AlphabetListView` ![resizeToAvoidBottomInset](https://private-user-images.githubusercontent.com/48699936/274684258-dd889266-8f2b-44f3-8e59-edf3f68f0d20.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNjI3MzMsIm5iZiI6MTcwNDI2MjQzMywicGF0aCI6Ii80ODY5OTkzNi8yNzQ2ODQyNTgtZGQ4ODkyNjYtOGYyYi00NGYzLThlNTktZWRmM2Y2OGYwZDIwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDA2MTM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNzMzNTAxMjI0NWFhYTJlNGU5MGFiZTgxYzA0OTdkMDhiMzU4NTBiNzVhNTU2NDMxNDIyM2M4MGUzMWQ0MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SK8vu_eH2wISr2_DfmrECDoia4XiEYyEuq8rKh0OYM4)

Okay, I'll give it a try. Thank you
